version: '2'
services:
  my-scala-app:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - postgres=postgres
    depends_on:
      - postgres
    volumes:
      - ./:/usr/tp
      - .cache/:/root/.cache # trick to save coursier (sbt) cache

  metabase: # https://www.metabase.com/learn/getting-started/getting-started.html
    image: metabase/metabase:latest
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: user
      MB_DB_PASS: password
      MB_DB_HOST: postgres
      MB_DB_FILE: "/metabase-data/metabase.db" # https://www.metabase.com/docs/latest/operations-guide/running-metabase-on-docker.html#mounting-a-mapped-file-storage-volume
      JAVA_TIMEZONE: Europe/Paris
    depends_on:
      - postgres

  postgres:
    image: postgres:13.6
    container_name: postgres
    ports:
      - "5432:5432"
    hostname: postgres
    volumes:
      - './pgdata:/var/lib/postgresql/data' # persist data https://stackoverflow.com/a/41650891/3535853
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: metabase
      POSTGRES_PASSWORD: password